# Generated by Django 2.0 on 2017-12-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('imageSource', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
                ('weakness', models.CharField(max_length=20)),
                ('strength', models.CharField(max_length=20)),
                ('maxAlcohol', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefensiveCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('imageSource', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OffensiveCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('imageSource', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('imageSource', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
                ('type', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
